[package]
name = "gotham_examples_templating_askama"
version = "0.0.0"
publish = false
edition = "2018"

[dependencies]
gotham = { path = "../../../gotham" }
askama = { version = "0.11.0", default-features = false }
