[package]
name = "gotham_examples_templating_askama"
version = "0.0.0"
publish = false
edition = "2018"

[dependencies]
gotham = { path = "../../../gotham" }
askama = "0.11.0"

# see comment in the workspace root
nom = "=6.2.0"
