[package]
name = "gotham_examples_middleware_introduction_await"
description = "Introduces the Middleware and Pipeline concepts provided by the Gotham web framework with async-await"
version = "0.0.0"
publish = false
edition = "2018"

[dependencies]
gotham = { path = "../../../gotham" }
