[package]
name = "gotham_examples_finalizer"
description = "A finalizer example application for working with Gotham."
version = "0.0.0"
publish = false
edition = "2018"

[dependencies]
gotham = { path = "../../gotham" }
